[package]
name = "geoindex"
version = "0.1.0"
authors = ["Jacek Całusiński <forger@forger.pl>"]
edition = "2018"

[dependencies]
hashbrown = "0.5.0"
geo = "0.12.2"
rstar = "0.4.0"
num-traits = "0.2.8"

[dev-dependencies]
criterion = "0.2.11"

[[bench]]
name = "lookup"
harness = false

